spring.application.name=emplify-backend

# --- CONFIGURACION DE BASE DE DATOS ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/emplify_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# --- CONFIGURACION JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACION DE SERIALIZACION ---
spring.jackson.serialization.fail-on-empty-beans=false