server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Forzar la lectura de tipos MIME (CSS, JS, etc)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Para la navegación de Angular/Ionic (ej. /home, /login)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Para evitar que un CSS o JS roto devuelva el index.html por error
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf)$ {
        try_files $uri =404;
        expires max;
        log_not_found off;
    }
}
